In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key
from IPython.display import display

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
import os
file_path = os.path.join("weather_data", "cities.csv")
city_data_df = pd.read_csv(file_path)
city_data_df.head()

,City_ID,City,Date,Lat,Lng,Max Temp,Humidity,Country,Cloudiness,Wind Speed
0,0,Port Elizabeth,2022-03-25 01:11:07,-33.9180,25.5701,64.09,99,ZA,100,10.36
1,1,Lagos,2022-03-25 01:07:29,6.5833,3.7500,81.36,83,NG,100,6.22
2,2,Severo-Kurilsk,2022-03-25 01:11:08,50.6789,156.1250,30.15,67,RU,99,9.95
3,3,Kyabe,2022-03-25 01:11:08,9.4515,18.9449,84.02,40,TD,83,2.30
4,4,Busselton,2022-03-25 01:11:09,-33.6500,115.3333,72.00,41,AU,36,12.84

In [3]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Date,Lat,Lng,Max Temp,Humidity,Country,Cloudiness,Wind Speed
0,0,Port Elizabeth,2022-03-25 01:11:07,-33.9180,25.5701,64.09,99,ZA,100,10.36
1,1,Lagos,2022-03-25 01:07:29,6.5833,3.7500,81.36,83,NG,100,6.22
2,2,Severo-Kurilsk,2022-03-25 01:11:08,50.6789,156.1250,30.15,67,RU,99,9.95
3,3,Kyabe,2022-03-25 01:11:08,9.4515,18.9449,84.02,40,TD,83,2.30
4,4,Busselton,2022-03-25 01:11:09,-33.6500,115.3333,72.00,41,AU,36,12.84

In [4]:
city_data_df.dtypes

City_ID         int64
City           object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Country        object
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [6]:
# To avoid any errors in the future - google does not take in negative numbers 
# as weights - so we are replacing all the negative temps to 0

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))

In [7]:
# Heatmap of temperature

# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]

# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]

# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=3)

# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=[max(temp, 0) for temp in max_temp],
    dissipating=False, 
    max_intensity=300, 
    point_radius=4
)

# Add the heatmap layer.
fig.add_layer(heat_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=humidity, 
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df['Cloudiness']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = clouds,
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of percent wind speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df['Wind Speed']
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights = wind,
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.

fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [12]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Date,Lat,Lng,Max Temp,Humidity,Country,Cloudiness,Wind Speed
1,1,Lagos,2022-03-25 01:07:29,6.5833,3.7500,81.36,83,NG,100,6.22
3,3,Kyabe,2022-03-25 01:11:08,9.4515,18.9449,84.02,40,TD,83,2.30
8,8,Puerto Ayora,2022-03-25 01:11:10,-0.7393,-90.3518,78.76,80,EC,100,8.86
10,10,Avarua,2022-03-25 01:11:11,-21.2078,-159.7750,82.45,83,CK,75,4.61
11,11,Cabanas,2022-03-25 01:11:12,22.9758,-82.9219,78.44,71,CU,100,3.22
14,14,Butaritari,2022-03-25 01:10:46,3.0707,172.7902,80.67,71,KI,55,13.33
16,16,Beihai,2022-03-25 01:11:13,21.4833,109.1000,75.61,90,CN,87,10.96
19,19,Charlestown,2022-03-25 01:11:14,-32.9500,151.6667,75.85,79,AU,81,4.00
21,21,Itarema,2022-03-25 01:10:19,-2.9248,-39.9167,77.43,86,BR,35,7.25
23,23,Japura,2022-03-25 01:11:16,-0.3167,102.3500,79.65,85,ID,64,0.56

In [13]:
preferred_cities_df.isnull().count()

City_ID       160
City          160
Date          160
Lat           160
Lng           160
Max Temp      160
Humidity      160
Country       160
Cloudiness    160
Wind Speed    160
dtype: int64

In [14]:
preferred_cities_df

,City_ID,City,Date,Lat,Lng,Max Temp,Humidity,Country,Cloudiness,Wind Speed
1,1,Lagos,2022-03-25 01:07:29,6.5833,3.7500,81.36,83,NG,100,6.22
3,3,Kyabe,2022-03-25 01:11:08,9.4515,18.9449,84.02,40,TD,83,2.30
8,8,Puerto Ayora,2022-03-25 01:11:10,-0.7393,-90.3518,78.76,80,EC,100,8.86
10,10,Avarua,2022-03-25 01:11:11,-21.2078,-159.7750,82.45,83,CK,75,4.61
11,11,Cabanas,2022-03-25 01:11:12,22.9758,-82.9219,78.44,71,CU,100,3.22
...,...,...,...,...,...,...,...,...,...,...
562,562,Vanimo,2022-03-25 01:27:10,-2.6741,141.3028,86.77,63,PG,100,2.66
563,563,Pailon,2022-03-25 01:27:10,-17.6500,-62.7500,76.10,98,BO,100,6.13
570,570,Sao Jose Da Coroa Grande,2022-03-25 01:27:13,-8.8978,-35.1478,79.00,78,BR,100,3.31
571,571,Marsh Harbour,2022-03-25 01:27:14,26.5412,-77.0636,75.96,85,BS,68,19.62
575,575,Martapura,2022-03-25 01:27:17,-3.4167,114.8500,77.09,94,ID,20,0.00

In [15]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

            City Country  Max Temp      Lat       Lng Hotel Name
1          Lagos      NG     81.36   6.5833    3.7500
3          Kyabe      TD     84.02   9.4515   18.9449
8   Puerto Ayora      EC     78.76  -0.7393  -90.3518
10        Avarua      CK     82.45 -21.2078 -159.7750
11       Cabanas      CU     78.44  22.9758  -82.9219
14    Butaritari      KI     80.67   3.0707  172.7902
16        Beihai      CN     75.61  21.4833  109.1000
19   Charlestown      AU     75.85 -32.9500  151.6667
21       Itarema      BR     77.43  -2.9248  -39.9167
23        Japura      ID     79.65  -0.3167  102.3500

In [16]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
# Radius of the search
# Type - lodging is one of the key words for place types placed by gmaps api
# key - is your api key

In [17]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [18]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Lagos,NG,81.36,6.5833,3.7500,
3,Kyabe,TD,84.02,9.4515,18.9449,
8,Puerto Ayora,EC,78.76,-0.7393,-90.3518,Finch Bay Galapagos Hotel
10,Avarua,CK,82.45,-21.2078,-159.7750,Paradise Inn
11,Cabanas,CU,78.44,22.9758,-82.9219,Villa Luis Montesino y Anabel
...,...,...,...,...,...,...
562,Vanimo,PG,86.77,-2.6741,141.3028,Vahmoneh Lodge Vanimo
563,Pailon,BO,76.10,-17.6500,-62.7500,Alojamiento pailon
570,Sao Jose Da Coroa Grande,BR,79.00,-8.8978,-35.1478,Crôa Mares Hotel
571,Marsh Harbour,BS,75.96,26.5412,-77.0636,Abaco Beach Resort
575,Martapura,ID,77.09,-3.4167,114.8500,Montana Hotel Syariah

In [19]:
hotels

{'html_attributions': [],
 'next_page_token': 'Aap_uEAaJxZWU1udykFI7uDJvzNzXjOfr763CxM8yx3AHPqnuyse9WXp79LUAEkNOjQkdsWKCUXKcWJXOID5k4AaDiMEH9h1fg5gonO7Eirn2qXmyWJ_QD2qZViZ-N2wECP-5ZS1PvwKQmFnQG-a2fKZa9-2syzYKMinBfGh158Su_q16SVHrCyUHy9Aa4zdAxC7q5ptKQ0aQ8TBGcX2b_9v1OumaKCkBJSuhf5IAbemaDo0pnC_2uDBNEWF1e22WJJNm-qUQRsPG_yMsNN42zi8SkOAF2CpeQheVoC0dg_jEg2WjFgki3aBjVMQrrdPNfR2kGEiOnWFORNnZn7rrX8j-4uoJcighHynXjerZNl45Nu3BjPuYDgQ53q_g5BCvi8UWqy2JYV4f18VNAsi-Lr3KAdUufSJuSalmg5mhQXt96jn4IOx6aAWGtz3',
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4437441, 'lng': 114.8330672},
    'viewport': {'northeast': {'lat': -3.442399219708498,
      'lng': 114.8342382302915},
     'southwest': {'lat': -3.445097180291502, 'lng': 114.8315402697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Montana Hotel Syariah',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2250,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110072342554613878345">Nurul Huda</a>'],
     'photo_reference': 'Aap_uEBTk1PzGZkyPc8ul6SVFdq1R3nBk3oQ5Fjuz2WCM4HVFSISFp2fWThGZEPIpmCB3QcMqDMVr9hs15nill1JaogyBnDz7waQtJAQ3YH68PnlXuvTm2x_klsqZn2OpXqkMnHp_54hNBAf1Wso2hS63hqLW28jLvhTH1tD80h5spMdYAtr',
     'width': 4000}],
   'place_id': 'ChIJc1g4sXKB5i0RkDuH58jptnU',
   'plus_code': {'compound_code': 'HR4M+G6 Loktabat Utara, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR4M+G6'},
   'rating': 4.3,
   'reference': 'ChIJc1g4sXKB5i0RkDuH58jptnU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 948,
   'vicinity': 'Jalan Nangka No.3, Loktabat Utara'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4430556, 'lng': 114.825},
    'viewport': {'northeast': {'lat': -3.441590019708499,
      'lng': 114.8263504302915},
     'southwest': {'lat': -3.444287980291502, 'lng': 114.8236524697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Permata In',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 426,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102733187096670514713">Hotel Permata In</a>'],
     'photo_reference': 'Aap_uECuqcmiFGC2vMnuRR1RN2Bybn-afeoOtpd7det2GlAIgvq7Ix9bsHpxWfWyEYmfpBjsMFXnvhNf8SyHymHRjPTP7aR2WijrVk5aRUuoaakPyXDqfcS18odVBDMYX5upxxDTQkuDfNuAXeO1HIaAwL74p9c8EU-gi6OyT9t-Z3b83is',
     'width': 758}],
   'place_id': 'ChIJUdGHuXGB5i0RT-umWSHhlyM',
   'plus_code': {'compound_code': 'HR4F+QX Loktabat Utara, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR4F+QX'},
   'rating': 3.7,
   'reference': 'ChIJUdGHuXGB5i0RT-umWSHhlyM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 462,
   'vicinity': 'Jalan A. Yani No.KM.34 No.1, Loktabat Utara'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.443129400000001, 'lng': 114.8218981},
    'viewport': {'northeast': {'lat': -3.441710519708499,
      'lng': 114.8232437302915},
     'southwest': {'lat': -3.444408480291502, 'lng': 114.8205457697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Banjar Permai',
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/107380173547596851162">Joseph Silitonga</a>'],
     'photo_reference': 'Aap_uEBQK0JUVuEyRDwNt_bBWTDec21h_Trnl5-941lMZLHp3Yk2eGJkgPsmLh0sAjyPQvf2uinSQHhBCFHM8Ta773tWqzYMwc1lDxWx5rjOazYDhVmtsGQxZdKB3Xvp2COLfYwLw2JJu6XuYsn3bnEa_1octg4vpF2Qq0K-qZ3xQJBwDrSQ',
     'width': 4000}],
   'place_id': 'ChIJ41q9WtuD5i0Ry9QlnQ5-qJY',
   'plus_code': {'compound_code': 'HR4C+PQ Guntung Payung, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR4C+PQ'},
   'rating': 3.9,
   'reference': 'ChIJ41q9WtuD5i0Ry9QlnQ5-qJY',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 406,
   'vicinity': 'Jalan A. Yani KM 33,5, Luktabat selatan, Banjar Baru selatan, Guntung Payung'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4318377, 'lng': 114.8340902},
    'viewport': {'northeast': {'lat': -3.430470369708498,
      'lng': 114.8353857302915},
     'southwest': {'lat': -3.433168330291501, 'lng': 114.8326877697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Penginapan Cahaya Rahman Guest House Syariah Banjarbaru',
   'photos': [{'height': 3000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/117168104450116871996">Khaerun Nisa</a>'],
     'photo_reference': 'Aap_uEB9Qpkh05ebI8Wj_RCukycUZJuaIXTIXXt98R3JvOPK55Z4gp4sj-3ma0qYcoRHVSZxM37Xh3SKK36Mc0tdfeRm-7nJxnYBUp2DGHlwgF2ySSFGIRqNrCHudeQIUoyA6J11qTtJ3722-pUdEKv3b1YhlxQzm3xNSeGHHoF0I5BpSh5c',
     'width': 4000}],
   'place_id': 'ChIJ7d7bw6GB5i0R8NCkJvkHXG8',
   'plus_code': {'compound_code': 'HR9M+7J Loktabat Utara, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR9M+7J'},
   'rating': 4,
   'reference': 'ChIJ7d7bw6GB5i0R8NCkJvkHXG8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 60,
   'vicinity': 'Jalan Pangeran Suriansyah Ujung No No.24CR, Loktabat Utara'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4125886, 'lng': 114.8493614},
    'viewport': {'northeast': {'lat': -3.411233719708498,
      'lng': 114.8507572802915},
     'southwest': {'lat': -3.413931680291502, 'lng': 114.8480593197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'BERLIAN GUEST HOUSE SYARIAH & CAFE',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2393,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116707856611078869646">BERLIAN GUEST HOUSE SYARIAH &amp; CAFE</a>'],
     'photo_reference': 'Aap_uECS-NPIXEk3JmPbHzsk1BUAM0zx5_SWzATA_1FmQ6UaTcGmirlYwrFtCsGKd3x-W0SBp7U6CQsVu8J1_fQpjPE1ENLTRLe4AFCVgo7orMJ589BXsRPtezhGztGwWh-CLttHDtpyEtIYdgHYS5GzPygAQwZAonDP4XFTYS3x6xvMGWE2',
     'width': 3222}],
   'place_id': 'ChIJJ0a2QMmB5i0RlBzRnqkzt_g',
   'plus_code': {'compound_code': 'HRPX+XP Cindai Alus, Banjar Regency, South Kalimantan, Indonesia',
    'global_code': '6P8PHRPX+XP'},
   'rating': 4.2,
   'reference': 'ChIJJ0a2QMmB5i0RlBzRnqkzt_g',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 287,
   'vicinity': 'Jalan A. Yani No.km39, RW.5, Cindai Alus'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.412726699999999, 'lng': 114.8517303},
    'viewport': {'northeast': {'lat': -3.411420569708498,
      'lng': 114.8529947302915},
     'southwest': {'lat': -3.414118530291501, 'lng': 114.8502967697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Kost Putri Hasanah/Distributor HWI/MCI Martapura',
   'photos': [{'height': 669,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115128373687988455286">Kost Putri Hasanah/Distributor HWI/MCI Martapura</a>'],
     'photo_reference': 'Aap_uEBjQEnt9hLYRppYK9ae3n5FA9-0oJ_Kn1ST-7LJefLIhJ0zWv5z6YPGtiz3w4HV0WHD_PxNxQcK75APLWKUuiHY00CSnHkppVvX1qejtbypGjv3q8G8gAP4Ht4UQUogvLKSSIw1psxwGU6sUVggrxn3MQgPG4bn_qlHydPvlq-mjIhC',
     'width': 719}],
   'place_id': 'ChIJRz9t6MuB5i0R-VfpVUiCqow',
   'plus_code': {'compound_code': 'HVP2+WM Tanjung Rema, Banjar Regency, South Kalimantan, Indonesia',
    'global_code': '6P8PHVP2+WM'},
   'rating': 4.2,
   'reference': 'ChIJRz9t6MuB5i0R-VfpVUiCqow',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 6,
   'vicinity': 'Jalan Sultan Adam No.26, RT.02/RW.01, Tanjung Rema'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.406459, 'lng': 114.846897},
    'viewport': {'northeast': {'lat': -3.405082419708498,
      'lng': 114.8482286802915},
     'southwest': {'lat': -3.407780380291502, 'lng': 114.8455307197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hotel Raudhatul Husna',
   'photos': [{'height': 3936,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111219041888985578530">wisma husna</a>'],
     'photo_reference': 'Aap_uEAJJqRqa3FnyHb_q1BgJVDpppJGL6EZVhe29Pt52_hQM1IFXZtwAXglzh-Hm42eXeQmidirzDWhusBklyZkF89bKz-eZ4pofsgH8NSU-jU_3OMSdNOU_o5IUxdE896jECbVQtWHPZqQ7lEbBsHXJqx-Vf63rPmx7niVhyrOp_bJ8WFz',
     'width': 5248}],
   'place_id': 'ChIJXbmnI9CB5i0Rw5D6OhgaeKM',
   'plus_code': {'compound_code': 'HRVW+CQ Cindai Alus, Banjar Regency, South Kalimantan, Indonesia',
    'global_code': '6P8PHRVW+CQ'},
   'rating': 4.2,
   'reference': 'ChIJXbmnI9CB5i0Rw5D6OhgaeKM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 187,
   'vicinity': 'Jalan Sasaran No.18A, Keraton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4031514, 'lng': 114.840196},
    'viewport': {'northeast': {'lat': -3.401666369708498,
      'lng': 114.8416337802915},
     'southwest': {'lat': -3.404364330291502, 'lng': 114.8389358197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Asrma Padang Guru Qamuli',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 2448,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109370792881167184257">THE LIBERATOR</a>'],
     'photo_reference': 'Aap_uEAN4OsFQvf6XGD1sUwyLG5bl5c_krgZ6gjYht6diarPc0EKfoB9Xk5W1i3Umdb86pveO6OqC1F6RsElvUTUNKJFI0MEmkhulJuiRFJ6UfYgrIXn2Tqfi06YBA9UHk6uMAc3pmWE8r-T6m-pMpU2pBXmdxqWea-C3xcTTqzx7fgaj6jz',
     'width': 3264}],
   'place_id': 'ChIJ5RCQPtqB5i0RKO_1HZgo6Ho',
   'plus_code': {'compound_code': 'HRWR+P3 Cindai Alus, Banjar Regency, South Kalimantan, Indonesia',
    'global_code': '6P8PHRWR+P3'},
   'rating': 4.4,
   'reference': 'ChIJ5RCQPtqB5i0RKO_1HZgo6Ho',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 36,
   'vicinity': 'Jalan Pisangan, Cindai Alus'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4215593, 'lng': 114.8688817},
    'viewport': {'northeast': {'lat': -3.420266769708498,
      'lng': 114.8702402802915},
     'southwest': {'lat': -3.422964730291502, 'lng': 114.8675423197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Buaya Kuning Team',
   'photos': [{'height': 3264,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/112251024662249485061">Echon 6678</a>'],
     'photo_reference': 'Aap_uECtGikdOT4UDGUGpDUN1eznNhAs6V04dMiyRryN0NnwhStrS4iYNyZoZH33BAR55Oyh_DgXOjz2LtrImD1Az9Vc7MbJ1V79D47P1AYdsPuZ9mDnKqxpafjmuL4xXwPCIEj9du7uY9R_E0S4cnVh_92IVoQxM8yYjavWubySnQi7OC48',
     'width': 2448}],
   'place_id': 'ChIJ43tMY0-A5i0Rx9NceDopvRU',
   'plus_code': {'compound_code': 'HVH9+9H Sungai Paring, Banjar Regency, South Kalimantan, Indonesia',
    'global_code': '6P8PHVH9+9H'},
   'rating': 4.1,
   'reference': 'ChIJ43tMY0-A5i0Rx9NceDopvRU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 11,
   'vicinity': 'jl.pintu air komp griya anggrek merah IV blok A no 28 martapura, Sungai Paring'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4390744, 'lng': 114.8478493},
    'viewport': {'northeast': {'lat': -3.437653019708498,
      'lng': 114.8492057302915},
     'southwest': {'lat': -3.440350980291501, 'lng': 114.8465077697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Griya Duta Hotel',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 808,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/101830405401679148078">Griya Duta Hotel</a>'],
     'photo_reference': 'Aap_uEAWfqYbbMWzSB9Uw5VZFPuevLVaPvboXdNw5WDc09wvnoH6k-W2uh4PX5cGWZ9A7p-fnoWraRY8Qgk1_ePdzW9OsNQratsHJnMH6uLdbRWjRH-rbMHwmhSjSdwnEw9RVycKM5HZ9SfVIivmX-8uJcvoGnDoVRXIXF7yLTpx6jTv3CT6',
     'width': 1435}],
   'place_id': 'ChIJY6F6jsmB5i0RtvCCvSQhH9E',
   'plus_code': {'compound_code': 'HR6X+94 Loktabat Utara, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR6X+94'},
   'rating': 3.9,
   'reference': 'ChIJY6F6jsmB5i0RtvCCvSQhH9E',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 362,
   'vicinity': 'Jl. A. Yani KM. 36.8, No. 26, Loktabat Utara'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4507866, 'lng': 114.8484501},
    'viewport': {'northeast': {'lat': -3.449384219708498,
      'lng': 114.8498109802915},
     'southwest': {'lat': -3.452082180291502, 'lng': 114.8471130197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'asrama mahasiswa kalteng bjb',
   'photos': [{'height': 720,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/102868135405898792438">Anjung Harapan</a>'],
     'photo_reference': 'Aap_uEDu7PwNKvZudpEg2iKx7YQUCWxqLxG_kvDpmj5USd0WdGmJM78g34ohiuC7TcPQumu-qkD6rfNZpVvu5vXLkUV1fDJvZ4BneWcc2XeM-ViCOZ_wzbscZlqeWIJjK0uleqDmqXMeGU0M-2bm29OUaNEmzesy0My8ObVc6wgHicV1iWAO',
     'width': 1280}],
   'place_id': 'ChIJN6_pAhmB5i0RbXp9H2qwM4U',
   'plus_code': {'compound_code': 'GRXX+M9 Sungai Besar, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PGRXX+M9'},
   'rating': 3,
   'reference': 'ChIJN6_pAhmB5i0RbXp9H2qwM4U',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4,
   'vicinity': 'Gang Kasturi, Sungai Besar'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.440482, 'lng': 114.823407},
    'viewport': {'northeast': {'lat': -3.439117319708499,
      'lng': 114.8246999802915},
     'southwest': {'lat': -3.441815280291503, 'lng': 114.8220020197085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Riyadh Guest House',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1536,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/116064832443983326147">Riyadh Guest House</a>'],
     'photo_reference': 'Aap_uEDcvI0bx4r1FwCxsxAUych_E4bAN4XpgXsuci-6dyEDKVdgEfJ_sQjweP6cjZqZeh3R0VBUXABpb1p6qMiKO29BXRsbnvcnqfEYmjgkRgcuZxE5FdKGZoMPGR-Qbok_EDpoactxlBYhsm3Sm3rXWTeLb3OSPwUM6vOwDUQcvwooW23m',
     'width': 2048}],
   'place_id': 'ChIJlxHAzHqD5i0RlgbzFJ3oov4',
   'plus_code': {'compound_code': 'HR5F+R9 Loktabat Utara, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR5F+R9'},
   'rating': 4.2,
   'reference': 'ChIJlxHAzHqD5i0RlgbzFJ3oov4',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 326,
   'vicinity': 'Jl. A. Yani KM.33,3 Komplek, Jalan Citra Megah Raya I, Loktabat Utara'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.452558, 'lng': 114.8399152},
    'viewport': {'northeast': {'lat': -3.451219569708498,
      'lng': 114.8412629302915},
     'southwest': {'lat': -3.453917530291502, 'lng': 114.8385649697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/generic_business-71.png',
   'icon_background_color': '#7B9EB0',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/generic_pinlet',
   'name': 'MG KOST DAN KANTOR SERKOLINAS',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1080,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/104833590581203679831">Neva Frea</a>'],
     'photo_reference': 'Aap_uECD0ACA3L-qwHv8n3Ov-JMgmoWeuJ8WRXC6wGkbyzgypaEPizoxPDAIkT2tqK6-P2n3Zud7uXakUX-1KhrquHQXiwXtFBQ7jvdrPVB4oXItpSBqD0XQP2fph3AQvGhXu_4a4DWROKjXD37U1bJpW08YowkbWEcKVdaX4QcZ3iOW-ea-',
     'width': 1920}],
   'place_id': 'ChIJ2cKUDRaB5i0RBT29fN4tsz8',
   'plus_code': {'compound_code': 'GRWQ+XX Loktabat Selatan, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PGRWQ+XX'},
   'rating': 4.3,
   'reference': 'ChIJ2cKUDRaB5i0RBT29fN4tsz8',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 19,
   'vicinity': 'Loktabat Selatan'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4392335, 'lng': 114.8492785},
    'viewport': {'northeast': {'lat': -3.437816919708498,
      'lng': 114.8506288302915},
     'southwest': {'lat': -3.440514880291502, 'lng': 114.8479308697085}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Grand Dafam Q Hotel Banjarbaru || DHM Syariah',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 4000,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/111896362170266577511">Grand Dafam Q Hotel Banjarbaru || DHM Syariah</a>'],
     'photo_reference': 'Aap_uEAPQ4tGHPZiLVeXOxTDII9LWl6rwsrEzns70N9aT7BAgB3QKNniYTkjEPqGl-wDehVJXOwHzyvabll0j6uBpEtlHOEXKNSPC2G_GIVHL-mODW3H7T7ir8i7qFJdIZJIvVWsixQOSzUE-2C464_AlUBsHnX4QkmtGrfYAJUgYogNdDMT',
     'width': 6000}],
   'place_id': 'ChIJ0UwPHASB5i0Rh-62fxkHfso',
   'plus_code': {'compound_code': 'HR6X+8P Komet, Banjarbaru City, South Kalimantan, Indonesia',
    'global_code': '6P8PHR6X+8P'},
   'rating': 4.5,
   'reference': 'ChIJ0UwPHASB5i0Rh-62fxkHfso',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 4352,
   'vicinity': 'Q Mall, Jalan A. Yani No.km 36.8, Komet'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': -3.4159928, 'lng': 114.8505537},
    'viewport': {'northeast': {'lat': -3.414682019708498,
      'lng': 114.8519112802915},

In [20]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [21]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [22]:
info_box_template = """
<dl>
<dt>Name</dt><dd>{column1}</dd>
<dt>Another name</dt><dd>{column2}</dd>
</dl>
"""

In [23]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [24]:
# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [25]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))